language: go

sudo: required
dist: trusty

env:
  - PGVERSION=9.1
  - PGVERSION=9.2
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5

go:
  - 1.5.3
  - 1.6
  - tip

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION

before_script:
  - createdb -V
  - createdb pq_types

script: go test -v -check.v
